[tool.poetry]
name = "template"
version = "0.1.0"
description = ""
authors = ["Cássio Jandir Pagnoncelli <cassiopagnoncellI@gmail.com>"]
readme = "README.md"
package-mode = false

# Core/production dependencies
[tool.poetry.dependencies]
python = ">=3.13,<4.0"
python-dotenv = "<2.0.0"
ipython = ">=9.2.0,<10.0.0"
prettyprinter = "<1.0.0"
fastapi = {extras = ["standard"], version = "<1.0.0"}
fastapi-mail = ">=1.4.2,<2.0.0"
uvicorn = "*"
pydantic = "<3.0.0"
pydantic-settings = "<3.0.0"
sqlmodel = "<1"
psycopg2-binary = ">=2.9.10,<3.0.0"
celery = "<6.0.0"
redis = "<7.0.0"
jinja2 = "<4.0.0"
passlib = "<2.0.0"
python-multipart = "<1.0.0"
requests = "<3.0.0"
websockets = ">=15.0.1,<16.0.0"
pyjwt = "<3.0.0"
minio = "<8.0.0"
boto3 = "<2.0.0"
ruamel-yaml = "<1.0.0"
wand = "<1.0.0"
sendgrid = ">=6.12.0,<7.0.0"
ipdb = "<1.0.0"
dj-database-url = "<3.0.0"
bcrypt = ">=4.3.0,<5.0.0"
user-agents = ">=2.2.0,<3"
geoip2 = "*"
asyncpg = ">=0.30.0"
tortoise-orm = {version = "0.20.0", extras = ["postgresql"]}
aerich = ">=0.7.0"
aiosqlite = ">=0.17.0"
colorama = ">=0.4.6"
inflect = ">=7.5.0"
tortoise-cli = ">=0.1.2"
pytest-asyncio = ">=0.26.0"
dill = ">=0.4.0"


[tool.poetry.group.dev.dependencies]
flower = "<3.0.0"  # Celery monitoring
pylint = ">=3.3.7,<4.0.0"


# Testing dependencies
[tool.poetry.group.test.dependencies]
pytest = "<9.0.0"
vcrpy = ">=7.0.0,<8.0.0"
pytest-asyncio = ">=0.23.0"


[tool.aerich]
tortoise_orm = "config.core.tortoise_db.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "asyncio: mark test as asyncio to run with pytest-asyncio"
]
