[project]
name = "template"
version = "0.1.0"
description = ""
authors = [
    {name = "Cássio Jandir Pagnoncelli",email = "cassiopagnoncellI@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython (>=9.2.0,<10.0.0)",
    "pylint (>=3.3.7,<4.0.0)",
    "fastapi (<1)",
    "fastapi[standard] (<1)",
    "uvicorn (<1)",
    "alembic (<2)",
    "python-dotenv (<2)",
    "pydantic (<3)",
    "pydantic-settings (<3)",
    "sqlmodel (<1)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "celery (<6)",
    "redis (<7)",
    "flower (<3)",
    "pytest (<9)",
    "wand (<1)",
    "pyjwt (<3)",
    "minio (<8)",
    "boto3 (<2)",
    "jinja2 (<4)",
    "ruamel-yaml (<1)",
    "prettyprinter (<1)",
    "ipdb (<1)",
    "passlib (<2)",
    "python-multipart (<1)",
    "requests (<3)",
    "websockets (>=15.0.1,<16.0.0)",
    "sendgrid (>=6.12.0,<7.0.0)",
    "vcrpy (>=7.0.0,<8.0.0)",
    "fastapi-mail (>=1.4.2,<2.0.0) ; python_full_version >= \"3.8.1\" and python_version < \"4.0\""
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
