development:
  url: {{ BROKER_URL }}
  result_backend: {{ BROKER_RESULT_BACKEND }}

test:
  url: {{ BROKER_URL }}
  result_backend: {{ BROKER_RESULT_BACKEND }}

production:
  url: {{ BROKER_URL }}
  result_backend: {{ BROKER_RESULT_BACKEND }}
