development:
  driver: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: ${APP_NAME}_development

test:
  driver: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: ${APP_NAME}_test

production:
  driver: postgresql
  host: ${DB_HOST}
  port: 5432
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  database: ${APP_NAME}_production
