development:
  endpoint: http://localhost:9000
  access_key: minio
  secret_key: minio
  bucket: local
  region: us-east-1

production:
  endpoint: https://s3.amazonaws.com
  access_key: minio
  secret_key: minio
  bucket: s3
  region: us-east-1
