#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp seed
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################

function run_seed() {
  cd "$PROJECT_ROOT"
  poetry run python db/seed.py
}

############################################################
# Main Script
############################################################
run_seed
