#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp tortoise
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################
function run_tortoise() {
  cd "$PROJECT_ROOT"
  params=("$@")
  source "$PROJECT_ROOT/venv/bin/activate"
  PYTHONPATH="$PROJECT_ROOT" tortoise-cli -c config.core.tortoise_db.TORTOISE_ORM shell"
}

run_tortoise "$@"
