#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp console
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "SERP: ${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
TEMPLATE_DIR="$SCRIPT_DIR/template"
PROJECT_ROOT=$(command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git rev-parse --show-toplevel || ([ -d /app ] && echo /app || pwd))

############################################################
# Main Script
############################################################

function run_console() {
  source "$PROJECT_ROOT/venv/bin/activate"
  PYTHONPATH="$PROJECT_ROOT" poetry run python lib/core/console/main.py "$@"
}

run_console "$@"
