#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp update
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################

function run_update() {
  git fetch template
  git checkout template/main -- .
  git commit -m "Serp edge"
  git log --oneline
}

run_update
