#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp flower
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################

function run_jobs_ui() {
  cd "$PROJECT_ROOT"
  celery -A config.initializers.broker flower
}

############################################################
# Main Script
############################################################
run_jobs_ui
