#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp test
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################
function run_tests() {
  cd "$PROJECT_ROOT"
  params=("$@")
  source "$PROJECT_ROOT/venv/bin/activate"
  if [ ${#params[@]} -eq 0 ]; then
    PYTHONPATH="$PROJECT_ROOT" APP_ENV=test poetry run pytest \
      tests/api \
      tests/jobs \
      tests/models \
      tests/services \
      tests/utils \
      -v
  else
    PYTHONPATH="$PROJECT_ROOT" APP_ENV=test poetry run pytest "${params[@]}" -v
  fi
}

run_tests "$@"
