#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp redis
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_ROOT=$(command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git rev-parse --show-toplevel || ([ -d /app ] && echo /app || pwd))

############################################################
# Main Script
############################################################

function run_redis_cli() {
  URL=$(PYTHONPATH="$PROJECT_ROOT" poetry run python lib/core/redis_service/url.py)
  echo $URL
  redis-cli -u $URL
}

run_redis_cli
