#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp secret
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_ROOT=$(command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git rev-parse --show-toplevel || ([ -d /app ] && echo /app || pwd))

############################################################
# Main Script
############################################################

function run_secret() {
  source "$PROJECT_ROOT/venv/bin/activate"
  PYTHONPATH="$PROJECT_ROOT" poetry run python lib/core/crypto/secret.py
}

run_secret
