#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp task list
#~   serp task describe [task_name]
#~   serp task run [task_name] [task_args] [extra_args]
#~
#~
#~ OPTIONS
#~
#~   task_name    - The name of the task to run
#~   task_args    - The arguments to pass to the task (optional)
#~   extra_args   - Extra arguments to pass to the task (optional)
#~
#~ EXAMPLES
#~
#~   serp task list
#~   serp task describe serp.tasks.examples.hello_world
#~   serp task run greeting --param name=John --param title=Professor --no-db
#~
#~
#~   --help  - View these usage instructions

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
TEMPLATE_DIR="$SCRIPT_DIR/template"
PROJECT_ROOT=$(command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git rev-parse --show-toplevel || ([ -d /app ] && echo /app || pwd))

############################################################
# Main Script
############################################################

function run_task() {
  source "$PROJECT_ROOT/venv/bin/activate"
  PYTHONPATH="$PROJECT_ROOT" poetry run python lib/core/task/cli.py run "$@"
}

run_task "$@"
