#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp dbload
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################

function run_db_load() {
  PYTHONPATH="$PROJECT_ROOT" poetry run python lib/core/database_routines/dbload.py
}

run_db_load
