#!/usr/bin/env bash

set -e

#~ USAGE
#~ 
#~   serp COMMAND
#~
#~
#~ COMMANDS
#~
#~   new           - Set up a new serp project
#~
#~   console, c    - Open app console
#~   db            - Open Postgres console
#~   redis         - Open Redis console
#~   dev, s        - Run web server in development mode
#~   prod          - Run web server in production mode
#~   worker, w     - Run celery worker
#~
#~   test, tests   - Run the tests
#~   lint          - Run the linter
#~
#~   dbcreate      - Create the database
#~   [x]migrate    - Run the migrations
#~   [x]rollback   - Rollback the migrations
#~   seed          - Fills an empy local dev pgsql database with seed data
#~   [x]reset      - Wipes the dev pgsql database, recreates it clean from
#~                   migrations, and seeds it with seed data. Useful for clean
#~                   dev environment setup and for switching customer
#~                   enviromnets in local development.
#~
#~   redismon      - Run Redis monitor (https://redis.io/commands/monitor/)
#~   flower        - Run Flower (Celery's monitor UI)
#~
#~   secret        - Generate a secure random secret
#~
#~   tasks         - List available tasks
#~   task          - Run task
#~
#~   help          - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
TEMPLATE_DIR="$SCRIPT_DIR/templates"

############################################################
# Main Script
############################################################
if [[ $# -lt 1 ]]; then
  usage
  exit 2
fi

command="$1"
shift 1
params=("$@")
case "$command" in
  new)
    "$SCRIPT_DIR/serp-new" "${params[@]}"
    exit 0
    ;;

  # Help.
  --help|help)
    usage | ${PAGER:-less}
    exit 0
    ;;

  # Processes.
  c|console)
    "$SCRIPT_DIR/serp-console" "${params[@]}"
    exit 0
    ;;

  db)
    "$SCRIPT_DIR/serp-db" "${params[@]}"
    exit 0
    ;;

  redis)
    "$SCRIPT_DIR/serp-redis-cli" "${params[@]}"
    exit 0
    ;;

  s|dev)
    "$SCRIPT_DIR/serp-dev" "${params[@]}"
    exit 0
    ;;

  p|prod)
    "$SCRIPT_DIR/serp-prod" "${params[@]}"
    exit 0
    ;;

  w|worker)
    "$SCRIPT_DIR/serp-jobs" "${params[@]}"
    exit 0
    ;;

  # Tests.
  t|test)
    "$SCRIPT_DIR/serp-test" "${params[@]}"
    exit 0
    ;;

  l|lint)
    "$SCRIPT_DIR/serp-lint" "${params[@]}"
    exit 0
    ;;

  # Database commands.
  dbcreate)
    "$SCRIPT_DIR/serp-dbcreate" "${params[@]}"
    exit 0
    ;;

  migrate)
    "$SCRIPT_DIR/serp-migrate" "${params[@]}"
    exit 0
    ;;

  rollback)
    "$SCRIPT_DIR/serp-rollback" "${params[@]}"
    exit 0
    ;;  

  seed)
    "$SCRIPT_DIR/serp-seed" "${params[@]}"
    exit 0
    ;;

  reset)
    "$SCRIPT_DIR/serp-reset" "${params[@]}"
    exit 0
    ;;

  # Monitor tools
  redismon)
    "$SCRIPT_DIR/serp-redis-monitor" "${params[@]}"
    exit 0
    ;;

  flower)
    "$SCRIPT_DIR/serp-flower" "${params[@]}"
    exit 0
    ;;

  # Tasks.
  tasks)
    "$SCRIPT_DIR/serp-tasks" "${params[@]}"
    exit 0
    ;;

  task)
    "$SCRIPT_DIR/serp-task" "${params[@]}"
    exit 0
    ;;

  *)
    log "Unknown command: ${command}"
    usage
    exit 0
    ;;
esac
