#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp lint
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################

function run_lint() {
  cd "$PROJECT_ROOT"
  poetry run pylint app
}

run_lint
