#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp tasks [task_name]
#~
#~
#~ OPTIONS
#~
#~   task_name - The name of the task to describe
#~
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
TEMPLATE_DIR="$SCRIPT_DIR/template"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################

function list_tasks() {
  source "$PROJECT_ROOT/venv/bin/activate"
  task_name="$1"
  if [ "$task_name" != "" ]; then
    PYTHONPATH="$PROJECT_ROOT" poetry run python lib/core/task/cli.py describe "$task_name"
  else
    PYTHONPATH="$PROJECT_ROOT" poetry run python lib/core/task/cli.py list
  fi
}

list_tasks "$@"
