#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp new NAME
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "SERP: ${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
TEMPLATE_DIR="$SCRIPT_DIR/templates"

############################################################
# Main Script
############################################################

function new_app() {
  if [ "$$1" == "" ]; then
    echo "Give a project name as the first argument"
    exit 1
  fi

  mkdir $1
  cd $1

  # Initialize git repository
  git init
  git branch -M main

  # Use poetry for package management
  poetry init -n

  # Use virtualenv
  python -m venv venv
  source venv/bin/activate

  # Add common libraries
  poetry add fastapi uvicorn alembic dotenv

  # App structure
  mkdir -p tests config app/models app/schemas app/services app/utils app/db app/api app/core db

  cp $TEMPLATE_DIR/app/main.py app/main.py
  cp $TEMPLATE_DIR/README.md README.md

  # Use alembic for migrations
  alembic init db/migrations

  # Output project structure
  tree -L 2
}

############################################################
# Main Script
############################################################
if [[ $# -lt 1 ]] || [[ $1 == "--help" ]] || [[ $1 == "" ]]; then
  usage
  exit 2
else
  echo "Creating a Serp project with params: $@"
  new_app "$1"
fi
