#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp db
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
TEMPLATE_DIR="$SCRIPT_DIR/template"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################

function run_db_console() {
  cd "$PROJECT_ROOT"
  URL=$(poetry run python lib/core/dbconsole.py)

  CLEAN_URL="${URL#postgres://}"
  USER_PASS_HOST_PORT_DB=$(echo "$CLEAN_URL" | sed -E 's#([^:]+):([^@]+)@([^:]+):([0-9]+)/(.+)#\1 \2 \3 \4 \5#')
  read USER PASSWORD HOST PORT DBNAME <<< "$USER_PASS_HOST_PORT_DB"
  PGPASSWORD="$PASSWORD" psql -h $HOST -p $PORT -U $USER $DBNAME
}

############################################################
# Main Script
############################################################
run_db_console
