#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp redis
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################

function run_redis_cli() {
  cd "$PROJECT_ROOT"
  URL=$(poetry run python lib/core/redis_url.py)
  echo $URL
  redis-cli -u $URL
}

run_redis_cli
