#!/usr/bin/env bash

set -e

#~ USAGE
#~ 
#~   serp COMMAND
#~
#~
#~ COMMANDS
#~
#~   new           - Set up a new serp project
#~
#~   c, console    - Open app console
#~   db            - Open database console
#~   s, dev        - Run the serp server in development mode
#~   prod          - Run the serp server in production mode
#~   w, worker     - Run the serp worker
#~
#~   t, test       - Run the tests
#~   l, lint       - Run the linter
#~
#~   dbcreate      - Create the database
#~   migrate       - Run the migrations
#~   rollback      - Rollback the migrations
#~   seed          - Fills an empy local dev pgsql database with seed data
#~   reset         - Wipes the dev pgsql database, recreates it clean from
#~                   migrations, and seeds it with seed data. Useful for clean
#~                   dev environment setup and for switching customer
#~                   enviromnets in local development.
#~
#~   redis         - Open CLI access to the Redis instance
#~   redis:monitor - Run Redis monitor (https://redis.io/commands/monitor/)
#~
#~   help          - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
TEMPLATE_DIR="$SCRIPT_DIR/templates"

############################################################
# Main Script
############################################################
if [[ $# -lt 1 ]]; then
  usage
  exit 2
fi

command="$1"
shift 1
params=("$@")
case "$command" in
  new)
    "$SCRIPT_DIR/serp-new" "${params}"
    exit 0
    ;;

  # Help.
  --help|help)
    usage | ${PAGER:-less}
    exit 0
    ;;

  # Processes.
  c|console)
    "$SCRIPT_DIR/serp-console" "${params}"
    exit 0
    ;;

  db)
    "$SCRIPT_DIR/serp-db" "${params}"
    exit 0
    ;;

  s|dev)
    "$SCRIPT_DIR/serp-dev" "${params}"
    exit 0
    ;;

  p|prod)
    "$SCRIPT_DIR/serp-prod" "${params}"
    exit 0
    ;;

  w|worker)
    "$SCRIPT_DIR/serp-jobs" "${params}"
    exit 0
    ;;

  # Tests.
  t|test)
    "$SCRIPT_DIR/serp-test" "${params}"
    exit 0
    ;;

  l|lint)
    "$SCRIPT_DIR/serp-lint" "${params}"
    exit 0
    ;;

  # Database commands.
  dbcreate)
    "$SCRIPT_DIR/serp-create-db" "${params}"
    exit 0
    ;;

  *)
    log "Unknown command: ${command}"
    usage
    ;;
esac
