#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp tasks
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
TEMPLATE_DIR="$SCRIPT_DIR/template"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################

function run_task() {
  cd "$PROJECT_ROOT"
  PYTHONPATH="$PROJECT_ROOT" poetry run python -m lib.tasks.$1
}

run_task "$1"
