#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp cron
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
TEMPLATE_DIR="$SCRIPT_DIR/template"
PROJECT_ROOT=$(git rev-parse --show-toplevel)

############################################################
# Main Script
############################################################

function run_jobs_cron() {
  cd "$PROJECT_ROOT"
  source "$PROJECT_ROOT/venv/bin/activate"
  PYTHONPATH="$PROJECT_ROOT" celery -A config.core.broker beat
}

run_jobs_cron
