#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp update
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PROJECT_ROOT=$(command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git rev-parse --show-toplevel || ([ -d /app ] && echo /app || pwd))

############################################################
# Main Script
############################################################

function run_update() {
  # Fetch bin update
  git submodule update --init --recursive
  cd lib/bin && git pull && cd ../..

  # Fetch template update
  git fetch template
  git checkout template/main -- .
  git commit -m "Serp edge"
  git log --oneline
}

run_update
