#!/usr/bin/env bash

set -e

#~ USAGE
#~
#~   serp dev
#~
#~
#~ COMMANDS
#~
#~   --help  - View these usage instructions
#~

log() {
  echo "${1}"
}

usage() {
  grep '^#~' < "$0" | cut -c 3-
}

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
TEMPLATE_DIR="$SCRIPT_DIR/template"
PROJECT_ROOT=$(command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git rev-parse --show-toplevel || ([ -d /app ] && echo /app || pwd))

############################################################
# Main Script
############################################################

function run_dev_server() {
  source "$PROJECT_ROOT/venv/bin/activate"
  PORT=${PORT:-8000}
  PYTHONPATH="$PROJECT_ROOT" APP_ENV=development fastapi dev app/server.py --host 0.0.0.0 --port $PORT
}

run_dev_server
